spring:
  application:
    name: board

  datasource:
    url: jdbc:mariadb://localhost:3306/db1
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate

  thymeleaf:
    cache: false

server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

logging:
  level:
    sql: debug
    org.hibernate.type: trace
    com.chunjae.board: info

